<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css(array(
    $this->assetTheme('css/front.css'),
    $this->assetTheme('css/owl.carousel.css'),
    $this->assetTheme('css/jquery.fs.wallpaper.css'),
    $this->assetTheme('css/animate.css')

));

// Load js
$this->js($this->assetTheme('js/retina.js'));

// Load js footer
$this->footScript()->appendFile($this->assetTheme('js/jquery.easing.min.js'));
$this->footScript()->appendFile($this->assetTheme('js/classie.js'));
$this->footScript()->appendFile($this->assetTheme('js/cbpAnimatedHeader.js'));
$this->footScript()->appendFile($this->assetTheme('js/owl.carousel.js'));
$this->footScript()->appendFile($this->assetTheme('js/jquery.fs.wallpaper.js'));
$this->footScript()->appendFile($this->assetTheme('js/jquery.mixitup.js'));
$this->footScript()->appendFile($this->assetTheme('js/wow.min.js'));
$this->footScript()->appendFile($this->assetTheme('js/contact_me.js'));
$this->footScript()->appendFile($this->assetTheme('js/jqBootstrapValidation.js'));
$this->footScript()->appendFile($this->assetTheme('js/vitality.js'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'href'  => $this->favicon(),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(array('prefix' => array(array('label' => __('Home'), 'href' => $this->url('home')))));
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->

</head>
<?php if ($module == 'system') { ?>
    <body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> wallpaper-inititalized">
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-expanded">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#pi-system">
                    <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" class="img-responsive" alt="<?php echo _escape($sitename); ?>">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a class="page-scroll" href="#pi-system"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">درباره ما</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">خدمات</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#process">امکانات</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#customer">مشتریان</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">تماس با ما</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <header style="background-image: url('<?php echo $this->assetTheme('image/bg-header.jpg'); ?>');">
        <div class="scroll-down">
            <a class="btn page-scroll" href="#about"><i class="fa fa-angle-down fa-fw"></i></a>
        </div>
    </header>
    <section id="about">
        <div class="container wow fadeIn">
            <div class="row">
                <div class="col-md-5">
                    <img src="<?php echo $this->assetTheme('image/about.jpg'); ?>" class="img-responsive" alt="">
                </div>
                <div class="col-md-5 col-lg-offset-1">
                    <div class="btline btline-mora">
                        <h1><?php echo _escape($sitename); ?> - سامانه تعالی سازمانی</h1>
                    </div>
                    <!-- <hr class="colored"> -->
                    <ul>
                        <li><strong>در برگیرنده‌ی انواع مدل‌ها و معیارهای ارزیابی که سازمان می‌تواند از بین آن‌ها انتخاب کند</strong></li>
                        <li><strong>ارزیابی عملکرد تیم‌ها از لحاظ زمانی و کیفی توسط مدیر تعالی و سرارزیابان</strong></li>
                        <li><strong>دریافت گزارش‌های مدیریتی در حوزه‌ی نتایج، توانمندساز و خودارزیابی</strong></li>
                        <li><strong>دسترسی به اطلاعات وارد شده در هر زمان و مکان و بر روی دستگاه‌های مختلف</strong></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section id="services" class="bg-gray">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-lg-12 wow fadeIn">
                    <div class="btline btline-services">
                        <h2>خدمات</h2>
                    </div>
                    <!-- <p>List of our services</p> -->
                    <!-- <hr class="colored"> -->
                </div>
            </div>
            <div class="row content-row">
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".2s">
                    <div class="about-content">
                        <div class="text-center">
                            <i class="fa fa-pencil fa-4x"></i>
                            <h3>تدوین اظهارنامه</h3>
                        </div>
                        <div class="index-text"></div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".4s">
                    <div class="about-content">
                        <div class="text-center">
                            <i class="fa fa-users fa-4x"></i>
                            <h3>خودارزیابی</h3>
                        </div>
                        <div class="index-text"></div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".6s">
                    <div class="about-content">
                        <div class="text-center">
                            <i class="fa fa-bar-chart fa-4x"></i>
                            <h3> نمودارهای گرافیکی نتایج</h3>
                        </div>
                        <div class="index-text"></div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".8s">
                    <div class="about-content">
                        <div class="text-center">
                            <i class="fa fa-tasks fa-4x"></i>
                            <h3>پروژه‌های بهبود</h3>
                        </div>
                        <div class="index-text"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <aside class="cta-quote" style="background-image: url('<?php echo $this->assetTheme('image/bg-aside.jpg'); ?>');">
        <span class="quote">در هر کجا و با هر دستگاهی قابل دسترس</span>
    </aside>
    <section id="process" class="services">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-12 wow fadeIn">
                    <div class="btline btline-process">
                        <h2>امکانات</h2>
                    </div>
                    <!-- <hr class="colored"> -->
                </div>
            </div>
            <div class="row content-row">
                <div class="col-md-4 wow fadeIn" data-wow-delay=".2s">
                    <div class="media">
                        <div class="pull-left">
                            <i class="fa fa-file-text-o"></i>
                        </div>
                        <div class="media-body">
                            <h3 class="media-heading">تدوین اظهارنامه</h3>
                            <div class="index-text">با استفاده از این نرم‌افزار می‌توانید اظهارنامه‌ی سازمان خود را با استفاده از مدل‌ها و معیارهای مختلفی که از پیش در نرم‌افزار وارد شده با سرعت و درصد اطمینان بالاتری تهیه کنید</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 wow fadeIn" data-wow-delay=".4s">
                    <div class="media">
                        <div class="pull-left">
                            <i class="fa fa-pencil-square-o"></i>
                        </div>
                        <div class="media-body">
                            <h3 class="media-heading">خود ارزیابی</h3>
                            <div class="index-text">ارزیابان می‌توانند فرآیند خودارزیابی را به صورت online و خارج از سازمان انجام دهند.</div>
                            <div class="index-text">گزارش‌های مدیریتی مختلف شامل گزارش‌های: کلاسیک، نموداری مسیر حرکت سازمان، گزارش میزان انطباق رویکردها و نتایج با منطق رادار به تفکیک معیارها و زیرمعیارها میزان انطباق با اهداف تعریف شده در ابتدای مسیر</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 wow fadeIn" data-wow-delay=".6s">
                    <div class="media">
                        <div class="pull-left">
                            <i class="fa fa-envelope"></i>
                        </div>
                        <div class="media-body">
                            <h3 class="media-heading">داشبرد مدیریت</h3>
                            <div class="index-text">مدیرعامل و مدیران میانی به راحتی در هر زمان می‌توانند به اطلاعات دسترسی داشته و حرکت خود را در حوزه‌ی نتایج و توامندسازها به راحتی نظارت و بررسی نمایند.</li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
    <?php /* <section id="work" class="bg-gray clearfix">
        <div class="container text-center wow fadeIn">
            <div class="btline btline-portfolio">
                <h2>Portfolio</h2>
            </div>
            <!-- <hr class="colored"> -->
            <div class="row content-row clearfix">
                <div class="col-xs-12">
                    <div class="row clearfix">
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-1.jpg'); ?>" alt="LetterHead Set">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">LetterHead Set</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/letterhead" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-2.jpg'); ?>" alt="Brochure">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Brochure</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/brochure" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-3.jpg'); ?>" alt="Shopping bag">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Shopping bag</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/shopping+bag" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-4.jpg'); ?>" alt="Logo">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Logo</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/logo" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row clearfix">
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-5.jpg'); ?>" alt="Folder">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Folder</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/folder" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-6.jpg'); ?>" alt="Booth">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Booth</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/booth" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-7.jpg'); ?>" alt="Advertising">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Advertising</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/advertising" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row clearfix">
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-8.jpg'); ?>" alt="Catalog">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Catalog</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/catalog" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-9.jpg'); ?>" alt="Invitating and Greeting card">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Invitating and Greeting card</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/invitation+card+and+greeting+card" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-10.jpg'); ?>" alt="Packaging">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Packaging</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/packaging" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="work-item">
                                <img class="img-responsive" src="<?php echo Pi::url('upload/site-image/portfolio/p-11.jpg'); ?>" alt="Exhibition Stand">
                                <div class="work-caption font-alt">
                                    <h3 class="work-title">Exhibition Stand</h3>
                                    <div class="work-descr">
                                        <a href="http://www.saramadi.com/portfolio/tag/exhibition+stand" class="btn btn-outline-dark">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> */ ?>
    <?php /* <section class="portfolio-carousel wow fadeIn">
        <div class="item" style="background-image: url('image/bg-1.jpg')">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 col-md-push-8">
                        <div class="project-details">
                            <img src="<?php echo Pi::url('image/logo-1.png'); ?>" class="img-responsive client-logo" alt="">
                            <span class="project-name">Project Name</span>
                            <span class="project-description">Branding, Website Design</span>
                            <!-- <hr class="colored"> -->
                            <a href="#portfolioModal1" data-toggle="modal" class="btn btn-outline-light">View Details <i class="fa fa-long-arrow-right fa-fw"></i></a>
                        </div>
                    </div>
                    <div class="col-md-8 col-md-pull-4 hidden-xs">
                        <img src="<?php echo Pi::url('image/mobile-screens.png'); ?>" class="img-responsive portfolio-image" alt="">
                    </div>
                </div>
            </div>
        </div>
        <div class="item" style="background-image: url('image/bg-2.jpg')">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 col-md-push-8">
                        <div class="project-details">
                            <img src="<?php echo Pi::url('image/logo-2.png'); ?>" class="img-responsive client-logo" alt="">
                            <span class="project-name">Project Name</span>
                            <span class="project-description">Branding, Website Design</span>
                            <!-- <hr class="colored"> -->
                            <a href="#portfolioModal2" data-toggle="modal" class="btn btn-outline-light">View Details <i class="fa fa-long-arrow-right fa-fw"></i></a>
                        </div>
                    </div>
                    <div class="col-md-8 col-md-pull-4 hidden-xs">
                        <img src="<?php echo Pi::url('image/tablet-screens.png'); ?>" class="img-responsive portfolio-image" alt="">
                    </div>
                </div>
            </div>
        </div>
        <div class="item" style="background-image: url('image/bg-3.jpg')">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 col-md-push-8">
                        <div class="project-details">
                            <img src="<?php echo Pi::url('image/logo-1.png'); ?>" class="img-responsive client-logo" alt="">
                            <span class="project-name">Project Name</span>
                            <span class="project-description">Branding, Website Design</span>
                            <!-- <hr class="colored"> -->
                            <a href="#portfolioModal3" data-toggle="modal" class="btn btn-outline-light">View Details <i class="fa fa-long-arrow-right fa-fw"></i></a>
                        </div>
                    </div>
                    <div class="col-md-8 col-md-pull-4 hidden-xs">
                        <img src="<?php echo Pi::url('image/mobile-screens.png'); ?>" class="img-responsive portfolio-image" alt="">
                    </div>
                </div>
            </div>
        </div>
        <div class="item" style="background-image: url('image/bg-4.jpg')">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 col-md-push-8">
                        <div class="project-details">
                            <img src="<?php echo Pi::url('image/logo-2.png'); ?>" class="img-responsive client-logo" alt="">
                            <span class="project-name">Project Name</span>
                            <span class="project-description">Branding, Website Design</span>
                            <!-- <hr class="colored"> -->
                            <a href="#portfolioModal4" data-toggle="modal" class="btn btn-outline-light">View Details <i class="fa fa-long-arrow-right fa-fw"></i></a>
                        </div>
                    </div>
                    <div class="col-md-8 col-md-pull-4 hidden-xs">
                        <img src="<?php echo Pi::url('image/tablet-screens.png'); ?>" class="img-responsive portfolio-image" alt="">
                    </div>
                </div>
            </div>
        </div>
    </section> */ ?>
    <section id="customer" class="testimonials">
        <div class="container text-center wow fadeIn">
            <div class="btline btline-clients">
                <h2>مشتریان</h2>
            </div>
            <!-- <hr class="colored"> -->
            <div class="row content-row">
                <div class="col-lg-12">
                    <div class="testimonials-carousel">
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="<?php echo $this->assetTheme('image/faragostaresh.png'); ?>">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="contact" class="bg-dark">
        <div class="container text-center">
            <div class="btline btline-contact">
                <h2>تماس با ما</h2>
            </div>
            <!-- <hr class="colored"> -->
            <div class="row">
                <?php $locations = array(
                    'latitude'  => '35', // latitude number
                    'longitude' => '51', // longitude number
                    'zoom'      => '15', // zoom number
                    'title'     => 'سرامدی', // place title
                ); ?>
                <div class="col-lg-8 col-lg-offset-2">
                    <br />
                    <?php echo $this->googleMap($locations); ?>
                </div>
            </div>
            <div class="row">
                <div class="text-left col-md-6" data-rel="license">تمام حقوق  نرم افزار برای <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                <div class="text-right col-md-6" data-rel="license">طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
            </div>


        </div>
    </section>
    <?php /* <footer class="footer" style="background-image: url('<?php echo $this->assetTheme('image/bg-footer.jpg'); ?>')">
        <div class="container text-center footerbox">
            <div class="row">
                <div class="footer-bg clearfix">
                    <div class="col-md-4 contact-details">
                        <h4><i class="fa fa-phone-square"></i> Phone</h4>
                        <p>+9821 2271 5692</p>
                        <p>+9821 2267 3725</p>
                        <p>+9821 2267 9364</p>
                    </div>
                    <div class="col-md-4 contact-details">
                        <h4><i class="fa fa-map-marker"></i> Address</h4>
                        <p>Unit 3, No.21, Before Thirty-Third St., Kordestan Highway, Tehran- Iran.</p>
                    </div>
                    <div class="col-md-4 contact-details">
                        <h4><i class="fa fa-envelope"></i> Email</h4>
                        <p>info@moragraphic.com</p>
                        <p>peyman.moradian@gmail.com</p>
                    </div>
                    <div class="social">
                        <div class="col-lg-12">
                            <ul class="list-inline">
                                <li>
                                    <a href="#"><i class="fa fa-facebook fa-fw fa-2x"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-twitter fa-fw fa-2x"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-linkedin fa-fw fa-2x"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="copyright">
                    <div class="col-md-4 text-left">Development and design by <a title="FaraGostaresh" href="http://www.faragostaresh.com">FaraGostaresh</a></div>
                    <div class="col-md-8 text-right">All material © <a title="MoraGraphic" href="http://www.saramadi.com"> MoraGraphic</a></div>
                </div>
            </div>
        </div>
    </footer> */ ?>
    </body>
<?php } else { ?>
    <body id="pi-modules" class="pi-locale-<?php echo $locale; ?> wallpaper-inititalized">
    <header class="inpage-header">
        <nav class="navbar navbar-inverse navbar-fixed-top navbar-expanded">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand page-scroll" href="http://www.saramadi.com">
                        <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" class="img-responsive" alt="<?php echo _escape($sitename); ?>">
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="hidden">
                            <a href="http://www.saramadi.com"></a>
                        </li>
                        <li>
                            <a class="page-scroll" href="http://www.saramadi.com#about">درباره ما</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="http://www.saramadi.com#services">خدمات</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="http://www.saramadi.com#process">امکانات</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="http://www.saramadi.com#customer">مشتریان</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="http://www.saramadi.com#contact">تماس با ما</a>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
    <section id="pageinfo" class="container pi-main-container">
        <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
        <!-- Flash messenger -->
        <?php include $this->template('flash-messenger'); ?>
        <!-- Top head zone -->
        <?php if (!empty($blocks['0'])) { ?>
            <div class="pi-zone-0">
                <?php foreach ($blocks['0'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
        <?php } ?>
        <div class="row">
            <!-- Left zone -->
            <?php if (!empty($blocks['1'])) { ?>
                <div class="pi-zone-1 col-md-4">
                    <?php foreach ($blocks['1'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
            <div class="<?php
            if (isset($blocks['1']) && isset($blocks['8'])) {
                echo 'col-md-4';
            } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                echo 'col-md-8';
            } else {
                echo 'col-md-12';
            }
            ?>">
                <!-- Center top zone -->
                <?php if (isset($blocks['2'])) { ?>
                    <div class="pi-zone-2">
                        <?php foreach ($blocks['2'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                    <div class="row">
                        <div class="col-md-6 pi-zone-3">
                            <?php
                            if (isset($blocks['3'])) {
                                foreach ($blocks['3'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                        <div class="col-md-6 pi-zone-4">
                            <?php
                            if (isset($blocks['4'])) {
                                foreach ($blocks['4'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                    </div>
                <?php } ?>
                <!-- Module content starts -->
                <?php if (!empty($content)) { ?>
                    <div class="<?php echo $module; ?>">
                        <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                            <?php echo $content; ?>
                        </div>
                        <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                    </div>
                <?php } ?>
                <!-- Module content ends -->
                <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                    <div class="row">
                        <div class="col-md-6 pi-zone-5">
                            <?php
                            if (isset($blocks['5'])) {
                                foreach ($blocks['5'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                        <div class="col-md-6 pi-zone-6">
                            <?php
                            if (isset($blocks['6'])) {
                                foreach ($blocks['6'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                    </div>
                <?php } ?>
                <!-- Center bottom zone -->
                <?php if (isset($blocks['7'])) { ?>
                    <div class="pi-zone-7">
                        <?php foreach ($blocks['7'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
            <!-- Right zone -->
            <?php if (isset($blocks['8'])) { ?>
                <div class="col-md-4 pi-zone-8">
                    <?php foreach ($blocks['8'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
        </div>
        <!-- Bottom foot zone -->
        <?php if (isset($blocks['99'])) { ?>
            <div class="pi-zone-99">
                <?php foreach ($blocks['99'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
        <?php } ?>
    </section>
    <?php /* <footer class="footer" style="background-image: url('<?php echo $this->assetTheme('image/bg-footer.jpg'); ?>')">
        <div class="container text-center footerbox">
            <div class="row">
                <div class="footer-bg clearfix">
                    <div class="col-md-4 contact-details">
                        <h4><i class="fa fa-phone-square"></i> Phone</h4>
                        <p>+9821 2271 5692</p>
                        <p>+9821 2267 3725</p>
                        <p>+9821 2267 9364</p>
                    </div>
                    <div class="col-md-4 contact-details">
                        <h4><i class="fa fa-map-marker"></i> Address</h4>
                        <p>Unit 3, No.21, Before Thirty-Third St., Kordestan Highway, Tehran- Iran.</p>
                    </div>
                    <div class="col-md-4 contact-details">
                        <h4><i class="fa fa-envelope"></i> Email</h4>
                        <p>info@moragraphic.com</p>
                        <p>peyman.moradian@gmail.com</p>
                    </div>
                    <div class="social">
                        <div class="col-lg-12">
                            <ul class="list-inline">
                                <li>
                                    <a href="#"><i class="fa fa-facebook fa-fw fa-2x"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-twitter fa-fw fa-2x"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-linkedin fa-fw fa-2x"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="copyright">
                    <div class="col-md-4 text-left">Development and design by <a title="FaraGostaresh" href="http://www.faragostaresh.com">FaraGostaresh</a></div>
                    <div class="col-md-8 text-right">All material © <a title="MoraGraphic" href="http://www.saramadi.com"> MoraGraphic</a></div>
                </div>
            </div>
        </div>
    </footer> */ ?>
    </body>
<?php } ?>
</html>